import os
from playwright.sync_api import sync_playwright
ok=[]; bad=[]
def chk(c,m):
    (ok if c else bad).append(m)
with sync_playwright() as pw:
    b=pw.chromium.launch()

    # ── SYNTHESIS ──
    p=b.new_page(viewport={"width":1400,"height":900})
    p.goto("file://"+os.path.abspath("Group7_S2_Synthesis.html")); p.wait_for_timeout(500)
    n0 = p.locator(".slip").count(); chk(n0==45, "45 slips rendered (got %d)" % n0)
    chk(p.locator(".col").count()==6, "6 clusters")
    p.click('[data-filter="synth"]'); p.wait_for_timeout(200)
    n1 = p.locator(".slip").count(); chk(n1==41, "synthetic filter removes 4 (got %d)" % n1)
    p.click('[data-filter="synth"]'); p.wait_for_timeout(200)
    p.fill("#q","acronym"); p.wait_for_timeout(250)
    n2 = p.locator(".slip").count(); chk(n2==1, "search narrows to 1 (got %d)" % n2)
    p.fill("#q",""); p.wait_for_timeout(250)
    p.click("#realonly"); p.wait_for_timeout(200)
    chk(p.locator(".slip").count()==41, "real-evidence-only works")
    p.click("#realonly"); p.wait_for_timeout(200)
    p.locator(".slip").first.click(); p.wait_for_timeout(400)
    chk(p.get_attribute("#drawer","data-open")=="true", "drawer opens on a note")
    chk(len(p.inner_text("#dwho"))>5, "drawer shows the interview source")
    p.select_option("#dmove","F"); p.wait_for_timeout(300)
    nF = p.locator('.col[data-cluster="F"] .slip').count()
    chk(nF==10, "keyboard move reassigns cluster (F now %d)" % nF)
    p.keyboard.press("Escape"); p.wait_for_timeout(300)
    chk(p.get_attribute("#drawer","data-open")=="false", "Escape closes drawer")
    p.click("#reset"); p.wait_for_timeout(300)
    chk(p.locator('.col[data-cluster="F"] .slip').count()==9, "reset restores the board")
    p.click('[data-lane="both"]'); p.wait_for_timeout(600)
    n3 = p.locator("#jgrid polyline").count(); chk(n3==2, "overlay draws 2 traces (got %d)" % n3)
    chk(p.locator("#jwarn").is_visible(), "synthetic warning shows on the caregiver lane")
    p.click("#theme"); p.wait_for_timeout(200)
    chk(p.get_attribute("html","data-theme")=="dark", "theme toggle")
    ce = p.evaluate("!!document.querySelector('.col-name') && document.querySelector('.col-name').isContentEditable")
    chk(ce, "cluster names are editable")
    chk(p.evaluate("[...document.querySelectorAll('.col-name')].every(e=>e.scrollHeight<=e.clientHeight+2)"), "no cluster name is clipped")
    p.close()

    # ── IDEATION ──
    p=b.new_page(viewport={"width":1400,"height":900})
    p.goto("file://"+os.path.abspath("Group7_S2_Ideation.html")); p.wait_for_timeout(400)
    n4 = p.locator(".card").count(); chk(n4==22, "22 concepts (got %d)" % n4)
    p.click('[data-dir="A"]'); p.wait_for_timeout(300)
    nA = p.locator('.card[data-dim="false"]').count()
    chk(nA==6, "direction A lights 6 (got %d)" % nA)
    p.click('[data-dir="B"]'); p.wait_for_timeout(300)
    nB = p.locator('.card[data-dim="false"]').count()
    chk(nB==8, "direction B lights 8 incl. concierge (got %d)" % nB)
    p.click('[data-dir="held"]'); p.wait_for_timeout(300)
    nH = p.locator('.card[data-dim="false"]').count()
    chk(nH==7, "held-back shows 7 (got %d)" % nH)
    p.click('[data-dir=""]'); p.wait_for_timeout(200)
    p.click('[data-tag="PHY"]'); p.wait_for_timeout(250)
    nV = p.locator(".card:visible").count()
    chk(nV==15, "PHY filter hides 7 (got %d)" % nV)
    p.click('[data-tag="PHY"]'); p.wait_for_timeout(200)
    chk(p.locator(".dir").count()==3, "3 direction panels")
    chk(p.locator(".gatebar").count()==3, "every direction carries a failure condition")
    p.close(); b.close()
print("PASS:")
for m in ok: print("  ✓",m)
if bad:
    print("FAIL:")
    for m in bad: print("  ✗",m)
